### ISSUE TITLE
投稿フォームをウィンドウで表示を有効にした状態でメンションに対して返信をするとウィンドウが閉じない

### ISSUE THREAD

**Issue by kagatiki** [shrimpia/misskey#32]
Ebisskey独自機能の
設定→全般→投稿フォームをウィンドウとして表示をオン
の状態でメンション対しリプライを送った後ウィンドウが閉じない。

**Comment by EbiseLutica** [comment]
ウィンドウ版の投稿フォームが自動で閉じられないのは仕様です〜。
